const { defineModel, fields } = require("@oondemand/oon-core-back");
const { withOptions } = require("../lib/model");

const ETAPAS = [
  "recebida",
  "validando_evento",
  "carregando_os_cliente",
  "identificando_perfil",
  "obtendo_cotacao",
  "gerando_documento",
  "anexando_omie",
  "enviando_email",
  "gerando_adiantamento",
  "atualizando_etapa_omie",
  "concluida",
  "aguardando_retry",
  "falha_operacional",
  "cancelada",
];

const entry = defineModel({
  name: "Fatura",
  singular: "fatura",
  basePath: "/faturas",
  schema: {
    chaveIdempotencia: withOptions(fields.string({ required: true, label: "Chave de Idempotência" }), { unique: true }),
    empresaOmie: fields.ref("EmpresaOmie", { required: true, label: "Empresa Omie" }),
    eventoWebhook: fields.ref("EventoWebhook", { required: true, label: "Evento de Origem" }),
    codigoOS: fields.string({ required: true, label: "Código da OS" }),
    numeroOS: fields.string({ label: "Número da OS" }),
    etapaOrigem: fields.string({ required: true, label: "Etapa de Origem" }),
    codigoClienteOmie: fields.string({ label: "Código do Cliente" }),
    nomeCliente: fields.string({ label: "Cliente" }),
    emailCliente: fields.string({ label: "E-mail do Cliente" }),
    paisCliente: fields.string({ label: "País" }),
    perfilFaturamento: fields.ref("PerfilFaturamento", { label: "Perfil de Faturamento" }),
    modeloDocumento: fields.ref("ModeloDocumento", { label: "Modelo" }),
    versaoModelo: fields.ref("VersaoModeloDocumento", { label: "Versão do Modelo" }),
    idioma: fields.enum(["pt-BR", "en-US", "es-ES"], { default: "pt-BR", label: "Idioma" }),
    moeda: fields.enum(["BRL", "USD", "EUR"], { default: "BRL", label: "Moeda" }),
    dataReferenciaCotacao: fields.date({ label: "Data de Referência" }),
    cotacaoMoeda: fields.ref("CotacaoMoeda", { label: "Cotação" }),
    cotacaoOficial: fields.number({ label: "Cotação Oficial", default: 1 }),
    tipoAjusteCotacao: fields.enum(["nenhum", "percentual", "valor_fixo"], { default: "nenhum", label: "Tipo de Ajuste" }),
    valorAjusteCotacao: fields.number({ label: "Valor do Ajuste", default: 0 }),
    cotacaoEfetiva: fields.number({ label: "Cotação Efetiva", default: 1 }),
    dadosOsSnapshotJson: fields.string({ label: "Snapshot da OS", searchable: false }),
    pdfBase64: fields.string({ label: "PDF", searchable: false }),
    pdfHash: fields.string({ label: "Hash do PDF", searchable: false }),
    nomeArquivo: fields.string({ label: "Nome do Arquivo" }),
    anexoOmieId: fields.string({ label: "ID do Anexo no Omie" }),
    destinatarios: fields.string({ label: "Destinatários" }),
    copias: fields.string({ label: "Cópias" }),
    providerMessageId: fields.string({ label: "ID da Mensagem" }),
    adiantamentoSolicitado: fields.boolean({ label: "Adiantamento Solicitado", default: false }),
    adiantamentoConfirmado: fields.boolean({ label: "Adiantamento Confirmado", default: false }),
    etapaAtual: fields.enum(ETAPAS, { required: true, default: "recebida", label: "Etapa Atual" }),
    status: fields.enum(["pendente", "em_processamento", "concluida", "aguardando_retry", "falha", "cancelada", "ignorada"], {
      required: true,
      default: "pendente",
      label: "Status",
    }),
    tentativas: fields.number({ label: "Tentativas", default: 0 }),
    proximaTentativaEm: fields.date({ label: "Próxima Tentativa" }),
    ultimoErroCodigo: fields.string({ label: "Código do Último Erro" }),
    ultimoErroMensagem: fields.string({ label: "Último Erro" }),
    acaoRecomendada: fields.string({ label: "Ação Recomendada" }),
    iniciadaEm: fields.date({ label: "Iniciada Em" }),
    concluidaEm: fields.date({ label: "Concluída Em" }),
    tempoProcessamentoMs: fields.number({ label: "Tempo de Processamento (ms)" }),
    motivoCancelamento: fields.string({ label: "Motivo do Cancelamento" }),
    observacaoProcessamento: fields.string({ label: "Observação de Processamento" }),
    lockUntil: fields.date({ label: "Lock Até" }),
    lockedBy: fields.string({ label: "Lock Por" }),
  },
  crud: { enabled: true, roles: { write: ["administrador", "gestor_faturamento", "operacao_faturamento"] } },
});

entry.mongooseModel.schema.index({ empresaOmie: 1, codigoOS: 1 });
entry.mongooseModel.schema.index({ status: 1, proximaTentativaEm: 1, lockUntil: 1 });
module.exports = entry;
